h 6 10
0 x1 1 -x1 2 x2 3 -x2 4 x3 5 -x3 6 x4 7 -x4 8 x5 9 -x5 10 x6 11 -x6 

0 True 0 False 7 False 
1 True 1 False 6 False 
2 True 0 False 8 False 
3 True 2 False 6 False 
4 True 3 False 9 False 
5 True 4 False 6 False 
6 True 1 False 2 False 3 False 
7 True 0 False 5 False 
8 True 4 False 5 False 
9 True 3 False 
10 True 6 False 
11 True 7 False 8 False 9 False 


c Metrics: 
c Crossbar size          : 12 x 10
c Write cycles(2n)       : 12
c MAC cycles(2^n)        : 64
